# Type: Azure Pipelines (YAML)
# Trigger: commits/merges to branch = 'main'
# Steps:
# 1. build and publish the .Net 8 web API project in the root of the repository
# 2. publish pipeline artifact of the dotnet publish output
# 3. Separate pipeline job: download pipeline artifact
# 4. Deploy artifact contents to App Service instance running on an ASE.  See details below for
#    environment configuration.  This step should use the pipeline task AzureWebApp@1
#
# Environment details
# App is hosted in an isolated tier App Serivce Plan running on an ASE
# ASE is isolated in a vnet so hosted agents cannot be used.  A private
# agent pool named 'sw-apim-agents' should be used.
# ASE name = ase-sw-apim
# App Service Plan name = asp-sw-apim
# App Service name = web-sw-apim
# Service Connection Name = 'Contoso3'

trigger:
  - main

jobs:
- job: Build
  displayName: 'Build and publish'
  pool:
    name: 'sw-apim-agents'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
    displayName: 'Install .Net 8 SDK'

  - script: dotnet build --configuration Release
    displayName: 'dotnet build'

  - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/publish
    displayName: 'dotnet publish'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/publish'
      artifact: 'web-api'
      publishLocation: 'pipeline'

- job: Deploy
  displayName: 'Deploy to ASE'
  dependsOn: Build
  pool:
    name: 'sw-apim-agents'
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: 'web-api'
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Contoso3'
      appName: 'web-sw-apim'
      package: '$(Pipeline.Workspace)/web-api'
      deploymentMethod: 'auto'
      appType: 'webApp'
      runtimeStack: 'DOTNETCORE|8.0'
      configurationStrings: '-ASPNETCORE_ENVIRONMENT Production'
      startUpCommand: 'dotnet WebApi.dll'
      deployToSlotOrASE: true
